kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mykind1
networking:
  # the default CNI will not be installed
  disableDefaultCNI: true
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  kubeProxyMode: "ipvs"
nodes:
- role: control-plane
  image: kindest/node:v1.31.0  # Match this with kubectl version
- role: worker
  image: kindest/node:v1.31.0  # Match this with kubectl version
  labels: 
    tier: infra
  extraPortMappings:
  - containerPort: 30090
    hostPort: 30090
    # optional: set the bind address on the host
    # 0.0.0.0 is the current default
    listenAddress: "0.0.0.0"
    # optional: set the protocol to one of TCP, UDP, SCTP.
    # TCP is the default
    protocol: TCP
- role: worker
  image: kindest/node:v1.31.0  # Match this with kubectl version
  labels: 
    tier: app
- role: worker
  image: kindest/node:v1.31.0  # Match this with kubectl version
  labels: 
    tier: app